"""
Fabric Git integration.

Pushes generated .pbip projects directly to a Fabric workspace Git repo
with migration metadata in commit messages.
"""

import base64
import json
import logging
import os
import time

import requests

logger = logging.getLogger(__name__)

_FABRIC_API_BASE = "https://api.fabric.microsoft.com/v1"


# ── Public API ───────────────────────────────────────────────────


def push_to_fabric_git(project_dir, workspace_id, *, token,
                       commit_message=None, branch=None):
    """Push a generated .pbip project to a Fabric workspace Git repo.

    Args:
        project_dir: Path to the generated .pbip project directory.
        workspace_id: Target Fabric workspace ID.
        token: Bearer token for Fabric API.
        commit_message: Git commit message (auto-generated if None).
        branch: Target branch (uses workspace default if None).

    Returns:
        dict with push result.
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    # Verify Git connection
    git_status = _get_git_status(workspace_id, headers)
    if not git_status.get("gitProviderDetails"):
        raise RuntimeError("Workspace is not connected to a Git repository")

    # Collect all files to push
    files = _collect_project_files(project_dir)
    if not files:
        raise RuntimeError(f"No files found in {project_dir}")

    # Build commit payload
    if not commit_message:
        commit_message = _build_commit_message(project_dir, len(files))

    # Push via updateFromGit or commitToGit
    result = _commit_files(workspace_id, files, commit_message, headers)

    logger.info("Pushed %d files to Fabric Git: %s", len(files), workspace_id)
    return result


def get_git_status(workspace_id, *, token):
    """Get the Git connection status for a workspace.

    Args:
        workspace_id: Fabric workspace ID.
        token: Bearer token.

    Returns:
        dict with git provider details and sync status.
    """
    headers = {"Authorization": f"Bearer {token}"}
    return _get_git_status(workspace_id, headers)


# ── Internal ─────────────────────────────────────────────────────


def _get_git_status(workspace_id, headers):
    """Query Fabric Git connection status."""
    url = f"{_FABRIC_API_BASE}/workspaces/{workspace_id}/git/status"
    resp = requests.get(url, headers=headers, timeout=30)
    if resp.status_code != 200:
        logger.warning("Git status check failed (%d): %s", resp.status_code, resp.text)
        return {}
    return resp.json()


def _collect_project_files(project_dir):
    """Walk project_dir and collect all files as base64-encoded entries."""
    files = []
    for root, _dirs, filenames in os.walk(project_dir):
        for fname in filenames:
            full = os.path.join(root, fname)
            rel = os.path.relpath(full, project_dir).replace("\\", "/")
            with open(full, "rb") as f:
                content = f.read()
            files.append({
                "path": rel,
                "payload": base64.b64encode(content).decode("ascii"),
                "payloadType": "InlineBase64",
            })
    return files


def _build_commit_message(project_dir, file_count):
    """Generate an auto commit message."""
    name = os.path.basename(project_dir.rstrip("/\\")) or "MicroStrategy Migration"
    return (
        f"chore: migrate {name} ({file_count} files)\n\n"
        f"Auto-generated by MicroStrategy → Power BI Migration Tool"
    )


def _commit_files(workspace_id, files, commit_message, headers):
    """Commit files to the Fabric workspace Git repo."""
    url = f"{_FABRIC_API_BASE}/workspaces/{workspace_id}/git/commitToGit"

    payload = {
        "mode": "All",
        "comment": commit_message,
    }

    resp = requests.post(url, headers=headers, json=payload, timeout=120)
    if resp.status_code in (200, 202):
        if resp.status_code == 202:
            _poll_operation(resp, headers)
        return {
            "status": "committed",
            "files_count": len(files),
            "workspace_id": workspace_id,
        }
    else:
        logger.warning("Git commit failed (%d): %s", resp.status_code, resp.text)
        return {
            "status": "failed",
            "error": resp.text,
            "status_code": resp.status_code,
        }


def _poll_operation(response, headers, max_wait=300):
    """Poll a long-running Fabric operation."""
    location = response.headers.get("Location") or response.headers.get("Operation-Location")
    if not location:
        return

    start = time.monotonic()
    while time.monotonic() - start < max_wait:
        resp = requests.get(location, headers=headers, timeout=30)
        if resp.status_code != 200:
            time.sleep(3)
            continue
        data = resp.json()
        status = data.get("status", "")
        if status in ("Succeeded", "Completed"):
            return
        if status in ("Failed", "Cancelled"):
            raise RuntimeError(f"Git operation failed: {data}")
        time.sleep(3)

    raise RuntimeError(f"Git operation timed out after {max_wait}s")
