"""
Fabric Spark notebook generator.

Generates PySpark notebooks that ETL data from MicroStrategy source
warehouses into Fabric Lakehouse Delta tables.
"""

import json
import logging
import os

logger = logging.getLogger(__name__)

# ── Spark data source format mapping ─────────────────────────────

_SPARK_FORMAT_MAP = {
    "sql_server": "jdbc",
    "oracle": "jdbc",
    "postgresql": "jdbc",
    "mysql": "jdbc",
    "teradata": "jdbc",
    "db2": "jdbc",
    "netezza": "jdbc",
    "snowflake": "snowflake",
    "databricks": "databricks",
    "bigquery": "bigquery",
    "sap_hana": "jdbc",
    "redshift": "jdbc",
}

_JDBC_DRIVER_MAP = {
    "sql_server": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "oracle": "oracle.jdbc.driver.OracleDriver",
    "postgresql": "org.postgresql.Driver",
    "mysql": "com.mysql.cj.jdbc.Driver",
    "teradata": "com.teradata.jdbc.TeraDriver",
    "db2": "com.ibm.db2.jcc.DB2Driver",
    "netezza": "org.netezza.Driver",
    "sap_hana": "com.sap.db.jdbc.Driver",
    "redshift": "com.amazon.redshift.jdbc42.Driver",
}

_JDBC_URL_TEMPLATE = {
    "sql_server": "jdbc:sqlserver://{server};databaseName={database};encrypt=true;trustServerCertificate=true",
    "oracle": "jdbc:oracle:thin:@{server}/{database}",
    "postgresql": "jdbc:postgresql://{server}/{database}",
    "mysql": "jdbc:mysql://{server}/{database}",
    "teradata": "jdbc:teradata://{server}/DATABASE={database}",
    "db2": "jdbc:db2://{server}/{database}",
    "netezza": "jdbc:netezza://{server}/{database}",
    "sap_hana": "jdbc:sap://{server}/?databaseName={database}",
    "redshift": "jdbc:redshift://{server}/{database}",
}


# ── Public API ───────────────────────────────────────────────────


def generate_notebooks(data, output_dir, *, lakehouse_name=None):
    """Generate Fabric Spark notebooks for ETL from source to Lakehouse.

    Generates one notebook per distinct source connection, each containing
    cells to load all tables from that connection into Delta tables.

    Args:
        data: dict with intermediate JSON data (datasources, freeform_sql).
        output_dir: Directory to write .ipynb files.
        lakehouse_name: Target Lakehouse name.

    Returns:
        dict with generation stats.
    """
    os.makedirs(output_dir, exist_ok=True)

    datasources = data.get("datasources", [])
    freeform_sql = data.get("freeform_sql", [])

    # Group tables by source connection
    conn_groups = {}
    for ds in datasources:
        conn = ds.get("db_connection", {})
        key = _conn_key(conn)
        conn_groups.setdefault(key, {"connection": conn, "tables": [], "freeform": []})
        conn_groups[key]["tables"].append(ds)

    for ffs in freeform_sql:
        conn = ffs.get("db_connection", {})
        key = _conn_key(conn)
        conn_groups.setdefault(key, {"connection": conn, "tables": [], "freeform": []})
        conn_groups[key]["freeform"].append(ffs)

    notebooks = []
    for i, (key, group) in enumerate(conn_groups.items(), 1):
        conn = group["connection"]
        db_type = (conn.get("db_type") or "unknown").lower()
        nb_name = f"etl_{db_type}_{i:02d}"

        cells = _build_notebook_cells(
            conn, group["tables"], group["freeform"],
            lakehouse_name=lakehouse_name,
        )

        notebook = _build_ipynb(nb_name, cells)
        nb_path = os.path.join(output_dir, f"{nb_name}.ipynb")
        with open(nb_path, "w", encoding="utf-8") as f:
            json.dump(notebook, f, indent=1, ensure_ascii=False)

        notebooks.append(nb_path)
        logger.info("Generated notebook: %s (%d tables)", nb_name, len(group["tables"]))

    return {
        "notebooks_generated": len(notebooks),
        "notebook_paths": notebooks,
    }


# ── Notebook construction ────────────────────────────────────────


def _build_notebook_cells(connection, tables, freeform_tables, *, lakehouse_name=None):
    """Build a list of notebook cells for a connection group."""
    db_type = (connection.get("db_type") or "").lower()
    server = connection.get("server", "")
    database = connection.get("database", "")
    schema = connection.get("schema", "")

    cells = []

    # Cell 1: Markdown header
    cells.append(_md_cell([
        f"# ETL: {db_type.upper()} → Fabric Lakehouse",
        "",
        f"**Source:** `{server}` / `{database}`  ",
        f"**Target:** Lakehouse{f' `{lakehouse_name}`' if lakehouse_name else ''}  ",
        f"**Tables:** {len(tables)} tables, {len(freeform_tables)} custom SQL views  ",
        "",
        "Auto-generated by MicroStrategy → Power BI Migration Tool",
    ]))

    # Cell 2: Connection setup
    spark_format = _SPARK_FORMAT_MAP.get(db_type, "jdbc")

    if spark_format == "jdbc":
        jdbc_url = _JDBC_URL_TEMPLATE.get(db_type, f"jdbc:{db_type}://{server}/{database}")
        jdbc_url = jdbc_url.format(server=server, database=database)
        driver = _JDBC_DRIVER_MAP.get(db_type, "")
        cells.append(_code_cell([
            "# Connection configuration",
            "# Update credentials before running",
            f'jdbc_url = "{jdbc_url}"',
            f'driver = "{driver}"',
            'properties = {',
            '    "user": "<USERNAME>",',
            '    "password": "<PASSWORD>",',
            f'    "driver": "{driver}",',
            '}',
        ]))
    elif spark_format == "snowflake":
        cells.append(_code_cell([
            "# Snowflake connection configuration",
            "sfOptions = {",
            f'    "sfUrl": "{server}",',
            f'    "sfDatabase": "{database}",',
            f'    "sfSchema": "{schema or "PUBLIC"}",',
            '    "sfUser": "<USERNAME>",',
            '    "sfPassword": "<PASSWORD>",',
            "}",
        ]))
    elif spark_format == "bigquery":
        cells.append(_code_cell([
            "# BigQuery connection configuration",
            f'bq_project = "{database}"',
            f'bq_dataset = "{schema}"',
        ]))

    # Cell 3+: Load each table
    for ds in tables:
        table_name = ds.get("physical_table") or ds["name"]
        delta_name = ds["name"]
        cells.append(_md_cell([f"## Table: `{delta_name}`"]))

        if spark_format == "jdbc":
            query = f"{schema}.{table_name}" if schema else table_name
            cells.append(_code_cell([
                f'# Load {table_name}',
                f'df_{delta_name} = spark.read.jdbc(',
                f'    url=jdbc_url,',
                f'    table="{query}",',
                f'    properties=properties',
                f')',
                f'',
                f'# Write to Delta table in Lakehouse',
                f'df_{delta_name}.write.format("delta").mode("overwrite").saveAsTable("{delta_name}")',
                f'print(f"✓ {delta_name}: {{df_{delta_name}.count()}} rows loaded")',
            ]))
        elif spark_format == "snowflake":
            cells.append(_code_cell([
                f'df_{delta_name} = spark.read.format("snowflake").options(**sfOptions).option("dbtable", "{table_name}").load()',
                f'df_{delta_name}.write.format("delta").mode("overwrite").saveAsTable("{delta_name}")',
                f'print(f"✓ {delta_name}: {{df_{delta_name}.count()}} rows loaded")',
            ]))
        elif spark_format == "bigquery":
            cells.append(_code_cell([
                f'df_{delta_name} = spark.read.format("bigquery").option("table", "{bq_project}.{bq_dataset}.{table_name}").load()',
                f'df_{delta_name}.write.format("delta").mode("overwrite").saveAsTable("{delta_name}")',
                f'print(f"✓ {delta_name}: {{df_{delta_name}.count()}} rows loaded")',
            ]))
        else:
            cells.append(_code_cell([
                f'# TODO: configure {db_type} connector for {table_name}',
                f'# df_{delta_name} = spark.read.format("{spark_format}").load()',
                f'# df_{delta_name}.write.format("delta").mode("overwrite").saveAsTable("{delta_name}")',
            ]))

    # Freeform SQL tables
    for ffs in freeform_tables:
        table_name = ffs["name"]
        sql = ffs.get("sql_statement", "")
        cells.append(_md_cell([f"## Custom SQL: `{table_name}`"]))

        if spark_format == "jdbc":
            # Escape the SQL for embedding
            safe_sql = sql.replace('"', '\\"').replace('\n', ' ')
            cells.append(_code_cell([
                f'# Load from custom SQL: {table_name}',
                f'query = "({safe_sql}) AS t"',
                f'df_{table_name} = spark.read.jdbc(',
                f'    url=jdbc_url,',
                f'    table=query,',
                f'    properties=properties',
                f')',
                f'df_{table_name}.write.format("delta").mode("overwrite").saveAsTable("{table_name}")',
                f'print(f"✓ {table_name}: {{df_{table_name}.count()}} rows loaded")',
            ]))
        else:
            cells.append(_code_cell([
                f'# Custom SQL for {table_name}:',
                f'# {sql[:100]}...',
                f'# TODO: Adapt this query for {db_type} Spark connector',
            ]))

    # Final summary cell
    total = len(tables) + len(freeform_tables)
    cells.append(_md_cell(["---", f"**ETL complete: {total} tables loaded into Lakehouse.**"]))

    return cells


def _build_ipynb(name, cells):
    """Build a Jupyter notebook dict."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Synapse PySpark",
                "language": "python",
                "name": "synapse_pyspark",
            },
            "language_info": {
                "name": "python",
                "version": "3.10",
            },
            "description": f"Auto-generated ETL notebook: {name}",
        },
        "cells": cells,
    }


def _md_cell(lines):
    """Create a markdown cell."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in lines],
    }


def _code_cell(lines):
    """Create a code cell."""
    return {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [line + "\n" for line in lines],
    }


def _conn_key(connection):
    """Create a hashable key for a connection dict."""
    return (
        (connection.get("db_type") or "").lower(),
        connection.get("server", ""),
        connection.get("database", ""),
    )
